### ISSUE TITLE
Mwt support in type names

### ISSUE THREAD

**Issue by mmulli** [phi-fell/mwt#1]
Is it feasible to add support the Mwt pattern within Type names, or is there some way to do this already that I've missed? For my specific use case I'd like to have the pattern work in the return type of a method (fn foo() -> ReturnTypeMwt). This is useful if you have mut and non mut variants of some guard type. 

If this is not already possible I'd be happy to take a stab at this and submit a pull request, though I may need some high level advice on how to approach it. My guess is that I should add a body to handle the case in the args.rs 'Type' match arm, and that I'd also need to handle the UpperCamelCase style of this use of Mwt?

And lastly, thank you for this crate! I hope this gets more visibility within the community so that more people recognize that an official solution is missing in the language. I wonder how much copy pasted mut / non mut code there is in the standard lib or how they have handled this.

**Comment by phi-fell** [comment]
I'm glad you're finding mwt useful!

So like you need it to return either `GuardStruct` or `GuardStructMut` rather than `&Mwt<>`?  This isn't supported, but it'll be a quick fix.

Pull requests are welcome but, in this case, it would probably take about as much time to give you an overview as it would to just add this myself - I'm not experienced enough with proc macros to point you at the exact spot without fiddling with some stuff anyway.

That said - I'm adding two things, type paths will now replace `Mwt` with `Mut` (or nothing) so `MyMwtGuardType` will become `MyMutGuardType` and `MyGuardType`.

To allow for other formats, I'm also adding `MwtAlt<A,B>` so you'll be able to do:
```Rust
#[mwt]
fn my_fun_mwt() -> MwtAlt<MutReturnValue, CompletelyDIfferentTypeForNonMut> {
    // fn body
}
```

I'll take suggestions on names if you don't like `MwtAlt` - I couldn't think of anything better.  The `#[maybe_mut]` version is probably going to be `MutOrElse<>` since that's a bit more descriptive, if longer.

v0.4 should be out later this evening unless something comes up.

---- P.S. ----
In case you're interested in making proc macros, the syn docs are really useful, a lot of stuff has unintuitive names (at least for someone like me who doesn't yet have in depth knowledge of rust internals).  That type match arm you pointed out is actually for [Expr::Type](https://docs.rs/syn/latest/syn/struct.ExprType.html) which is e.g. `foo: u64` and whatnot, i.e. not return types.  look into Expr vs. Item, etc. for top level items vs expressions.

(I'm actually only using that big ol' repetitive `match` at all because I need to be able to return one type of `Expr` as another, and the fold_etc() functions only support returning the same type.  There is likely a more elegant solution but this was what I could find looking through the docs)

For things that can return the same type (most stuff) -you can look through [syn::Fold](https://docs.rs/syn/latest/syn/fold/trait.Fold.html#provided-methods) and see the methods that can be used (there's a lot)

**Comment by phi-fell** [comment]
v0.4 is out with this feature, check the readme (towards the bottom, in the "what it's actually doing" section) for some details, or look at [the relevant test](https://github.com/phi-fell/mwt/blob/d2c26fd57b3ab1b71eed866eec02ed108cf7f68e/tests/maybe_mut.rs#L93-L134) for an example.

I'm gonna close this issue, but let me know if I missed something (or if anything doesn't work).

**Comment by mmulli** [comment]
Thanks for the quick feedback and update! I'm totally new to proc macros so appreciate the pointers. I'll be sure to give this update a try soon and let you know if there are any issues.
